---
name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments
exclude:
- Gemfile
- Gemfile.lock
- README
- Rakefile
- s3_website.yml
sitemap:
  file: /sitemap.xml
  exclude:
  - /robots.txt
  - /feed.xml
